### PR TITLE
fix: Fixed hardcoded class name for relocation

### PR DESCRIPTION
**Pull request by LeeGodSRC**
Followed what you said and I can relocate and run my plugin without issues, there could be other places with hardcoded names tho, just looks fine for me.

### CODE REVIEW

**Comment by LeeGodSRC** [comment]
#12

**Comment by bergerkiller** [comment]
Looks good. its a bit of a hacky system but can you also increment the version here? That way it gets a properly tagged version on the repository. Then I can merge it.

https://github.com/bergerhealer/Mountiplex/blob/master/build.gradle.kts#L7

**Comment by LeeGodSRC** [comment]
Bumped it!

**Comment by bergerkiller** [comment]
Oh im realizing that what you did here:
```
L" + MPLType.getInternalName(InvalidArgumentCountException.class) + ";"
```

Is better done with

MPLType.getDescriptor(InvalidArgumentCountException.class)

Can you change it? Both will work but the latter is more 'proper'

(omit the L and ; )

**Comment by LeeGodSRC** [comment]
> Oh im realizing that what you did here:
> 
> ```
> L" + MPLType.getInternalName(InvalidArgumentCountException.class) + ";"
> ```
> 
> Is better done with
> 
> MPLType.getDescriptor(InvalidArgumentCountException.class)
> 
> Can you change it? Both will work but the latter is more 'proper'
> 
> (omit the L and ; )

Fixed it! I was also wondering if there is a proper way for this too haha, not really experienced with bytecodes.

**Pull request merged**
